import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
          <div className="bcs-camera"></div>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <div className="hover:border-primario-400 mb-4 card-shipping relative xl:flex flex md:flex sm:flex-row items-center w-full px-[16px] rounded-l-lg shadow-lg select-none py-[20px] cursor-pointer rounded-r-xl bg-smmoth border border-azul_gris-80 active">
        <div className="icon-shipping h-[4.25rem] max-w-[4rem] max-h-[4.25rem] mim-w-[4rem] min-h-[4.25rem] mr-5 justify-center w-full flex items-center rounded-[0.75rem] bg-gris-90">
          <i className="icon-ds-bcs bcs-home text-[1.6875rem] text-primario-400"></i>
        </div>
        <label className="label-shipping" htmlFor="shipping-home">
          <div>
            <p className="text-[1.125rem] font-semibold leading-8 text-primario-900 m-0 tracking-normal">
              Label
            </p>
            <p className="font-light leading-[1.125rem] text-[0.875rem] m-0 tracking-normal text-azul_gris-100">
              Description
            </p>
          </div>
        </label>
        <label className="input-shipping radio">
          <input type="radio" name="radio" className="hidden" />
          <span className="hover:border-azul_gris-50 absolute inline-block w-8 h-8 bg-white border rounded-full top-[calc(50%-1rem)] right-4 check-border-check-blue border-azul_gris-80"></span>
        </label>
      </div>

      <footer className={styles.footer}>
        <i className="icon-ds-bcs bcs-home text-[3.6875rem] text-primario-400 text-red-500 font-bold"></i>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
