import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-sm w-full lg:max-w-full lg:flex">
        <div
          className="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden"
          title="Woman holding a mug"
        ></div>
        <div className="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
          <div className="mb-8">
            <p className="text-sm text-gray-600 flex items-center">
              <svg
                className="fill-current text-gray-500 w-3 h-3 mr-2"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
              >
                <path d="M4 8V6a6 6 0 1 1 12 0v2h1a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-8c0-1.1.9-2 2-2h1zm5 6.73V17h2v-2.27a2 2 0 1 0-2 0zM7 6v2h6V6a3 3 0 0 0-6 0z" />
              </svg>
              Members only
            </p>
            <div className="text-gray-900 font-bold text-xl mb-2">
              Can coffee make you a better developer?
            </div>
            <p className="text-gray-700 text-base">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Voluptatibus quia, nulla! Maiores et perferendis eaque,
              exercitationem praesentium nihil.
            </p>
          </div>
          <div className="flex items-center">
            <Image src="/vercel.svg" alt="Vercel Logo" width={50} height={50} />

            <div className="text-sm">
              <p className="text-gray-900 leading-none">Jonathan Reinink</p>
              <p className="text-gray-600">Aug 18</p>
            </div>
          </div>
        </div>
      </div>

      <div className="hover:border-primario-400 mb-4 card-shipping relative xl:flex flex md:flex sm:flex-row items-center w-full px-[16px] rounded-l-lg shadow-lg select-none py-[20px] cursor-pointer rounded-r-xl bg-smmoth border border-azul_gris-80 active">
        <div className="icon-shipping h-[4.25rem] max-w-[4rem] max-h-[4.25rem] mim-w-[4rem] min-h-[4.25rem] mr-5 justify-center w-full flex items-center rounded-[0.75rem] bg-gris-90">
          <i className="icon-ds-bcs bcs-home text-[1.6875rem] text-primario-400"></i>
        </div>
        <label className="label-shipping" htmlFor="shipping-home">
          <div>
            <p className="text-[1.125rem] font-semibold leading-8 text-primario-900 m-0 tracking-normal">
              Label
            </p>
            <p className="font-light leading-[1.125rem] text-[0.875rem] m-0 tracking-normal text-azul_gris-100">
              Description
            </p>
          </div>
        </label>
        <label className="input-shipping radio">
          <input type="radio" name="radio" className="hidden" />
          <span className="hover:border-azul_gris-50 absolute inline-block w-8 h-8 bg-white border rounded-full top-[calc(50%-1rem)] right-4 check-border-check-blue border-azul_gris-80"></span>
        </label>
      </div>
    </div>
  );
};

export default Home;
